# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Snippet"
description: > # this means to ignore newlines until "email:"
   This website includes "snippet" about kernel and vim and software-defined radio.
   I call the blogs as snippet because most of them are extremely short, simple, and irrelevant ideas.
   I don't know what the point of these ideas is for now, but I'll try to put them together into logical posts or projects.

email: hsy1995313@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/wuhan_huangjia_lake.jpg"

name: 'Shiyue He'
author: 'Shiyue He'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://octhe.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  # - icon:	twitter
  #   url:	https://twitter.com/dirkfabisch
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/octhe
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
