\input texinfo.tex @c -*- texinfo -*-

@setfilename index.html
@settitle Shiyue's Cardbox

@node index 
@top Cardbox Index

@include distribution.texi
@include desktop.texi
@include kernel.texi
@include blog.texi
@include shell.texi
@include editor.texi
@include network.texi
@include sdr.texi
@include input_method.texi

@bye
