\input texinfo.tex @c -*- texinfo -*-

@setfilename index.html
@settitle Shell Cottage

@node index 
@top Contents

This is a personal blog website that named as Shell Cottage.
The blog focuses on Linux platform and wireless network.

@include distribution.texi
@include desktop.texi
@include kernel.texi
@include blog.texi
@include shell.texi
@include editor.texi
@include network.texi
@include sdr.texi
@include input_method.texi

@bye
