@node Input Method
@chapter Input Method

This README is related to the chinese input method.
In openSUSE, the fcitx5 framework can be installed from the repository with command

@code{sudo zypper in fcitx5}

This command will install a GUI configuration tool @code{fcitx5-configtool}.
The chinese input method can be chosen from it.
