\input texinfo.tex @c -*- texinfo -*-

@setfilename index.html
@settitle OctHe's Blog

@node index 
@top Contents

This is a personal blog website.
The blog focuses on Linux platform and wireless network.

@include distribution.texi
@include desktop.texi
@include system.texi
@include kernel.texi
@include blog.texi
@include shell.texi
@include editor.texi
@include version_control.texi
@include server.texi
@include network.texi
@include sdr.texi
@include input_method.texi

@bye
