@node Network
@chapter Network

@section iw

iw is a configuration tool for mac80211 in Linux kernel with netlink
The code tree of @code{iw.c} in iw is

@itemize @bullet
@item main
    @itemize @minus
    @item version
    @item nl80211_init
        @itemize @minus 
        @item nl_socket_alloc
        @item nl_socket_free
        @item nl_socket_set_buffer_size
        @end itemize
    @item usage
        @itemize @minus 
        @item __usage_cmd
        @item usage_options
        @end itemize
    @item __handle_cmd
        @itemize @minus 
        @item error_handler
        @item finish_handler
        @item ack_handler
        @item register_handler
        @item valid_handler
        @item phy_lookup
        @end itemize
    @item phy_lookup
    @item nl80211_cleanup
    @end itemize
@item TOPLEVEL
    @itemize @minus 
    @item print_help
    @end itemize
@item handle_cmd
    @itemize @minus 
    @item __handle_cmd
    @end itemize
@item usage_cmd
    @itemize @minus 
    @item __usage_cmd
    @end itemize
@end itemize

@section proxy

Auto detect proxy with @code{nc} and connect to it

@example
if nc -z $<srv_ip> $<proxy_port>; then
    git config --global http.proxy "http://$<srv_ip>:$<proxy_port>"
    git config --global https.proxy "https://$<srv_ip>:$<proxy_port>"

elif nc -z $<local_ip> $<proxy_port>; then
    git config --global http.proxy "http://$<local_ip>:$<proxy_port>"
    git config --global https.proxy "https://$<local_ip>:$<proxy_port>"

else
    git config --global --unset http.proxy 
    git config --global --unset https.proxy
fi
@end example

@section snapdrop.net

@url{https://snapdrop.net, snapdrop} is an easily-used point-to-point file transfer in the web browser.
Open the link of snapdrop in the same network.
The website can identify all devices in the same network. 
Just drop the file to the target.
