#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# This script was generated by LLM.
# -----------------------------------------------------------------------------
# Description:
#   This script renames blog post files in the _posts directory so that
#   their filename begins with the file's modification date (YYYY-MM-DD-).
#   It operates on files that git reports as changed/untracked in _posts.
#   It preserves the original behavior exactly.
# -----------------------------------------------------------------------------

# Exit immediately if a command exits with a non-zero status (-e),
# treat unset variables as an error (-u), and make pipelines fail if any
# command in the pipeline fails (-o pipefail).
set -euo pipefail

# Change to the root directory of the git repository.
# `git rev-parse --show-toplevel` prints the absolute path to the repo root.
cd "$(git rev-parse --show-toplevel)"

# Define the directory containing the blog posts.
POSTS_DIR="_posts"

# Get a machine-readable, NUL-separated list of changed files in _posts.
# The -z option separates entries with NUL characters, which safely handles
# filenames containing spaces/newlines.
# Pipe each entry into a while loop; `IFS=` prevents whitespace trimming,
# `-r` prevents backslash escaping, and `-d ''` uses NUL as the delimiter.
git status --porcelain -z -- "$POSTS_DIR" | while IFS= read -r -d '' entry; do
  # Extract the first two characters of the entry as the git status code
  # (e.g., " M", "??", "R ", etc.).
  status="${entry:0:2}"

  # Extract the filename starting at index 3 (after the status code and space).
  file="${entry:3}"

  # If the status indicates a rename (R) or copy (C), the next NUL-separated
  # field is the original filename. Read and discard it to keep the stream
  # aligned. `|| true` prevents set -e from exiting if reading fails.
  case "$status" in
    R*|C*) IFS= read -r -d '' _orig || true ;;
  esac

  # Skip if the file does not exist (e.g., deleted files).
  [ -f "$file" ] || continue

  # Get the directory portion of the file path.
  dir=$(dirname -- "$file")

  # Get the base filename (without directory).
  base=$(basename -- "$file")

  # Extract the file extension (everything after the last dot).
  ext="${base##*.}"

  # Extract the filename without the extension.
  name="${base%.*}"

  # Remove an existing date prefix (YYYY-MM-DD-) from the name, if present.
  # The pattern matches any 4 chars, a hyphen, 2 chars, a hyphen, 2 chars,
  # and a hyphen at the start.
  name="${name#????-??-??-}"

  # Get the file's modification date in YYYY-MM-DD format.
  # `date -r` works on BSD/macOS; if it fails, fall back to GNU `stat -c %y`
  # and cut the date portion.
  mtime=$(date -r "$file" +%Y-%m-%d 2>/dev/null || stat -c %y "$file" | cut -d' ' -f1)

  # Build the new filename with the modification date as a prefix.
  newbase="${mtime}-${name}.${ext}"

  # If the new filename differs from the current one, rename the file.
  # `-v` prints what is being done; `--` ends option parsing.
  if [ "$base" != "$newbase" ]; then
    mv -v -- "$file" "$dir/$newbase"
  fi
done
